---
# tasks to complete before running roles
- name: Pre-run Setup
  hosts: all
  become: true
  pre_tasks:
    - name: Pre-run | Update package cache (debian, etc)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false
      when: ansible_facts['os_family'] | lower == 'debian'

    - name: Pre-run | Update package cache (archlinux, etc)
      community.general.pacman:
        update_cache: true
      changed_when: false
      when: ansible_facts['os_family'] | lower == 'archlinux'

# run roles
- name: Apply base role
  hosts: all
  roles:
    - base

- name: Apply roles to hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Include roles for each host
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ roles_to_run | default([]) }}"
      when: roles_to_run is defined

# end of run cleanup and reporting
- name: Cleanup
  hosts: all
  become: true
  tasks:
    - name: Cleanup package cache (debian and ubuntu)
      ansible.builtin.apt:
        autoclean: true
      changed_when: false
      when: ansible_facts['os_family'] | lower == 'debian'

    - name: Autoremove orphan packages (debian and ubuntu)
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_facts['os_family'] | lower == 'debian'
