---
# tasks to complete before running roles
- name: Bootstrap
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure collections are installed from requirements.yml
      ansible.builtin.command: ansible-galaxy install -r requirements.yml
      register: galaxy_result
      changed_when: "'was installed properly' in galaxy_result.stdout"
      delegate_to: localhost
      run_once: true  # noqa: run-once
      check_mode: false

    - name: Check 1Password session
      block:
        - name: Include 1Password check
          ansible.builtin.include_tasks: roles/base/tasks/check_1password.yml
      delegate_to: localhost
      run_once: true  # noqa: run-once

- name: Pre-run Setup
  hosts: all
  tasks:
    - name: Pre-run | Update package cache (apt-based systems)
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      ignore_errors: "{{ ansible_check_mode }}"
      when: ansible_facts.pkg_mgr | lower == 'apt'

    - name: Pre-run | Update package cache (pacman-based systems)
      become: true
      community.general.pacman:
        update_cache: true
      changed_when: false
      ignore_errors: "{{ ansible_check_mode }}"
      when: ansible_facts.pkg_mgr | lower == 'pacman'

    - name: Pre-run | Update Homebrew (macOS)
      community.general.homebrew:
        update_homebrew: true
      when: ansible_facts.pkg_mgr | lower == 'homebrew'

# run roles
- name: Apply base role
  hosts: all
  roles:
    - base
    - user_core

- name: Apply roles to hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Include roles for each host
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ roles_to_run | default([]) }}"
      when: roles_to_run is defined

# end of run cleanup and reporting
- name: Cleanup
  hosts: all
  post_tasks:
    - name: Cleanup package cache (debian and ubuntu)
      become: true
      ansible.builtin.apt:
        autoclean: true
      changed_when: false
      when: ansible_facts.pkg_mgr | lower == 'apt'

    - name: Autoremove orphan packages (debian and ubuntu)
      become: true
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_facts.pkg_mgr | lower == 'apt'
